/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Message, Message, AUTO)


PB_BIND(command_struct, command_struct, AUTO)


PB_BIND(orientation_ref_struct, orientation_ref_struct, AUTO)


PB_BIND(position_ref_struct, position_ref_struct, AUTO)





